name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        # IKKE mappe porter i Actions; bruk service-navn i stedet
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      # 👇 Viktig: bruk 'postgres' som host
      DATABASE_URL: postgresql+psycopg2://testuser:testpass@postgres:5432/testdb
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -p 5432 -U testuser -d testdb && break
            echo "Postgres not ready yet... ($i)"
            sleep 2
          done

      - name: Run tests
        run: pytest -q
