name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb -h 127.0.0.1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    env:
      DATABASE_URL: postgresql+psycopg2://testuser:testpass@127.0.0.1:5432/testdb
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: ${{ github.workspace }}
      PGPASSWORD: testpass

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Postgres client tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres (pg_isready + psql probe)
        run: |
          for i in {1..60}; do
            pg_isready -h 127.0.0.1 -p 5432 -U testuser -d testdb && \
            psql -h 127.0.0.1 -U testuser -d testdb -c "SELECT 1" >/dev/null && break
            echo "Postgres not ready yet... ($i)"; sleep 2
          done

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q
